'use strict';var f=this;
function g(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function h(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.d=function(a,c,m){for(var t=Array(arguments.length-2),l=2;l<arguments.length;l++)t[l-2]=arguments[l];return b.prototype[c].apply(a,t)}};function k(a){if(Error.captureStackTrace)Error.captureStackTrace(this,k);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}h(k,Error);k.prototype.name="CustomError";var n;function p(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}var u=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},v=/&/g,w=/</g,x=/>/g,y=/"/g,z=/'/g,A=/\x00/g,B=/[\x00&<>"']/;function C(a,b){return a<b?-1:a>b?1:0};function D(a,b){b.unshift(a);k.call(this,p.apply(null,b));b.shift()}h(D,k);D.prototype.name="AssertionError";function E(a,b){throw new D("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var F;a:{var G=f.navigator;if(G){var H=G.userAgent;if(H){F=H;break a}}F=""};function I(){return-1!=F.indexOf("Edge")};var J={e:!0},aa={f:!0};function K(){throw Error("Do not instantiate directly");}K.prototype.b=null;K.prototype.toString=function(){return this.a};var ba=-1!=F.indexOf("Opera")||-1!=F.indexOf("OPR"),L=-1!=F.indexOf("Edge")||-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"),M=-1!=F.indexOf("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&!I())&&!(-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"))&&!I(),ca=-1!=F.toLowerCase().indexOf("webkit")&&!I();function da(){var a=F;if(M)return/rv\:([^\);]+)(\)|;)/.exec(a);if(L&&I())return/Edge\/([\d\.]+)/.exec(a);if(L)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ca)return/WebKit\/(\S+)/.exec(a)}
function N(){var a=f.document;return a?a.documentMode:void 0}var O=function(){if(ba&&f.opera){var a=f.opera.version;return"function"==g(a)?a():a}var a="",b=da();b&&(a=b?b[1]:"");return L&&!I()&&(b=N(),b>parseFloat(a))?String(b):a}(),P={};
function Q(a){if(!P[a]){for(var b=0,c=u(String(O)).split("."),d=u(String(a)).split("."),e=Math.max(c.length,d.length),m=0;0==b&&m<e;m++){var t=c[m]||"",l=d[m]||"",ea=/(\d*)(\D*)/g,fa=/(\d*)(\D*)/g;do{var q=ea.exec(t)||["","",""],r=fa.exec(l)||["","",""];if(0==q[0].length&&0==r[0].length)break;b=C(0==q[1].length?0:parseInt(q[1],10),0==r[1].length?0:parseInt(r[1],10))||C(0==q[2].length,0==r[2].length)||C(q[2],r[2])}while(0==b)}P[a]=0<=b}}
var R=f.document,S=N(),ga=!R||!L||!S&&I()?void 0:S||("CSS1Compat"==R.compatMode?parseInt(O,10):5);var T;if(!(T=!M&&!L)){var U;if(U=L)U=L&&(I()||9<=ga);T=U}T||M&&Q("1.9.1");L&&Q("9");function ha(){this.a=f.document||document};L&&Q(8);function ia(){var a=V,b;b=(n||(n=new ha)).a.createElement("DIV");a=ja(a(ka,void 0,void 0));a.match(la);b.innerHTML=a;return 1==b.childNodes.length&&(a=b.firstChild,1==a.nodeType)?a:b}
function ja(a){var b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return String(a);if(a instanceof K){if(a.c===J)return a.a;if(a.c===aa)return a=a.a,B.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(v,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(w,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(x,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(y,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(z,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(A,"&#0;"))),a}E("Soy template output is unsafe for use as HTML: "+a);return"zSoyz"}
var la=/^<(body|caption|col|colgroup|head|html|tr|td|tbody|thead|tfoot)>/i,ka={};function W(){K.call(this)}h(W,K);W.prototype.c=J;var ma=function(a){function b(a){this.a=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.b=d);return e}}(W);(function(a){function b(a){this.a=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.b=d);return e}})(W);function V(){return ma('<div><form method="get" action="/_/list-autos"><p><select name="city"><option value="atlanta">Atlanta</option><option value="houston">Houston</option><option value="seattle">Seattle</option><option value="sfbay">SF &amp; Bay Area</option></select><input type="text" name="query" placeholder="Query..."><input type="submit"></p></form></div><div class="Ve We"><p><b>Price by Mileage</b><div id="chart-price-by-mileage"></div></div><div class="Ve We"><p><b>Price by Year</b><div id="chart-price-by-year"></div></div><div class="Ve We"><p><b>Mileage by Year</b><div id="chart-mileage-by-year"></div></div>')}
V.a="till.templates.container";function X(){}X.prototype.a=function(a,b){4==a.readyState&&b(a.status,a.statusText,a.responseText)};function Y(){this.c=new X;document.body.appendChild(ia());document.querySelector("form").addEventListener("submit",this.b.bind(this))}
Y.prototype.a=function(a,b,c){a=document.getElementsByClassName("Ve");b=0;for(var d=a.length;b<d;++b)a[b].classList.remove("We");b=/(\,|\r?\n|\r|^)(?:"([^"]*(?:""[^"]*)*)"|([^"\,\r\n]*))/gi;a=[[]];for(d=null;;){d=b.exec(c);if(!d)break;var e=d[1];e.length&&","!=e&&a.push([]);d=d[2]?d[2].replace(/""/g,'"'):d[3];a[a.length-1].push(d)}c="";b=0;for(d=a.length;b<d;++b)c+=a[b][2]+","+a[b][1]+"\n";Z("chart-price-by-year",c);c="";b=0;for(d=a.length;b<d;++b)c+=a[b][0]+","+a[b][1]+"\n";Z("chart-price-by-mileage",
c);c="";b=0;for(d=a.length;b<d;++b)c+=a[b][2]+","+a[b][0]+"\n";Z("chart-mileage-by-year",c)};
Y.prototype.b=function(a){a.preventDefault();for(var b=document.querySelectorAll("div.Ve"),c=0,d=b.length;c<d;++c)b[c].classList.add("We");b=a.target.querySelector("[name=city]").value;c=a.target.querySelector("[name=query]").value;a=this.c;b="/_/list-autos?city="+encodeURIComponent(b)+"&query="+encodeURIComponent(c);c=new XMLHttpRequest;c.onreadystatechange=a.a.bind(a,c,this.a.bind(this));c.open("GET",b,!0);c.send()};
function Z(a,b){new window.Dygraph(document.getElementById(a),b,{drawPoints:!0,strokeWidth:0})}new Y;
